import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import ContentLayout from "./contentLayout";
import { OtpProvider } from "@/context/OtpContext";
import QueryProvider from "@/providers/QueryProvider";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <QueryProvider>
            <OtpProvider>
              <CartProvider>
                <ContentLayout>
                  {children}
                </ContentLayout>
              </CartProvider>
            </OtpProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
